apiVersion: batch/v1
kind: Job
metadata:
  name: job-never-2
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 2
  template:
    metadata:
      name: job-never-2
    spec:
      restartPolicy: Never
      containers:
        - name: job-never-2
          image: ubuntu:16.04
          args:
            - sh
            - -c
            - echo job-never-2; sleep 5; false
