apiVersion: batch/v1
kind: Job
metadata:
  name: job-never-1
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    metadata:
      name: job-never-1
    spec:
      restartPolicy: Never
      containers:
        - name: job-never-1
          image: ubuntu:16.04
          args:
            - sh
            - -c
            - echo job-never-1; sleep 5; false
