apiVersion: batch/v1
kind: Job
metadata:
  name: job-never-0
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    metadata:
      name: job-never-0
    spec:
      restartPolicy: Never
      containers:
        - name: job-never-0
          image: ubuntu:16.04
          args:
            - sh
            - -c
            - echo job-never-0; sleep 5; false
