apiVersion: batch/v1
kind: Job
metadata:
  name: job-on-failure-2
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 2
  template:
    metadata:
      name: job-on-failure-2
    spec:
      restartPolicy: OnFailure
      containers:
        - name: job-on-failure-2
          image: ubuntu:16.04
          args:
            - sh
            - -c
            - echo job-on-failure-2; sleep 5; exit 1
